# Generated by Django 3.1.4 on 2021-06-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='owner',
        ),
    ]
